spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update